#!/bin/bash
# AutoEnum by Droogy
# scan for all ports on a target, parse those results and rescan the discovered ports

printf 'gimme target: '
read target
nmap -p- -T4 $target -oN portscan

# read portscan file output and turn into CSV formatted ports for nmap
cat portscan | grep open | cut -d '/' -f 1 | tr '\n' , > ports.txt

# read file into variable
ports=$(<ports.txt)

# script categories
# auth, broadcast, brute, default. discovery, dos, exploit \
# external, fuzzer, intrusive, malware, safe, version, and vuln
# should prob throw in UDP at some point
# -sU -top-ports 250

nmap -A -v -p$ports --script=discovery,vuln, brute \
--version-all $target -oN initial.log
clear
cat initial.log | grep tcp
